#server:
#  port: 8080
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/dbmallapp
    username: root
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      platform: mysql
---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/dbmallapp_qa
    username: root
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      platform: mysql
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/dbmallapp_prod
    username: root
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      platform: mysql